#!/bin/bash
#$1 is users dir $2 is working dir
export SHELL=/bin/bash
rm -f $1/gdl.log
rm -f $1/comm
rm -f $1/tmp*.png
rm  $1/scl*.png
rm  $1/hist*.png


pkill -9 -f "sh -c echo none"
pkill -9 -f "tail -f $1/comm"
pkill -9 -f "gdl -arg $1"
mkfifo $1/comm
#rm "$1/gdl.log"
tail -f $1/comm | (cd $1 && exec gdl -arg "$1" -arg "$2" "$2/qvud_launcher") > $1/gdl.log 2>&1
#tail -f $1/comm | gdl -arg "$1" ../../qvud_launcher > $1/gdl.log 2>&1
