function cosph_comp,a,ratio,howmany
;takes a (structure generated by cosph)
;makes a copy and multiplies by the ratio
;searches matches between a and a*ratio 
;return howmany best matches

print,"Calculating the matches.."

if not(keyword_set(howmany)) then howmany=50<(n_elements(a.rr)-1)
	
n=n_elements(a.r)

ar=reform(a.r,n)
ai=reform(a.i,n)
aj=reform(a.j,n)


ar=mreplicate(ar,n)
i=mreplicate(ai,n)
j=mreplicate(aj,n)
br=transpose(mreplicate((ratio*ar),n))
k=transpose(mreplicate((ai),n))
l=transpose(mreplicate((aj),n))

dif=ar-br

print,"Sorting by best match.."
s=(sort(abs(dif)))

dif=dif(s)
i=i(s)
j=j(s)
k=k(s)
l=l(s)



srtstr=string(i,format='(I04)')+string(j,format='(I04)')
u=uniq(srtstr)
dif=dif(u)
i=i(u)
j=j(u)
k=k(u)
l=l(u)

h=howmany-1

return,{dif:dif(0:h),i:i(0:h),j:j(0:h),k:k(0:h),l:l(0:h)}
end

function cosph_mx,n,hex=hex,square=square
;generates a matrix of nxn representing lattice points i,j and fills it with distances using the given metric
;metric - hex is default

print,"Generating the matrix.."
n=round((n>0)<50)
print, "n ="+string(n)
ii=mreplicate(lindgen(n),n)
jj=transpose(ii)

if keyword_set(square) then rr=ii^2+jj^2 $
	else rr=ii^2+jj^2+ii*jj 

return,{rr:rr,r:double(rr)^0.5,i:ii,j:jj}

end


function cosph,n,ratio,hex=hex,square=square,ls=ls,nres=nres
;parameters as in the previously defined functions (cosph_mx)
;ls list the result
;nres - the "howmany" of the cosph_comp

mx=cosph_mx(long(n),hex=hex,square=square)
t=cosph_comp(mx,ratio,nres)

if keyword_set(ls) then begin
n=n_elements(t.i)
for i=0,n-1 do print,t.i(i),t.j(i),t.k(i),t.l(i),t.dif(i)



end

return,t
end
